// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLDBXKCYwX-ika7dNY15oaoiV7rscYjzw',
    appId: '1:799466011826:web:eec2b518ec25f379aaddab',
    messagingSenderId: '799466011826',
    projectId: 'smart-bus-26302',
    authDomain: 'smart-bus-26302.firebaseapp.com',
    storageBucket: 'smart-bus-26302.appspot.com',
    measurementId: 'G-V2T7P8R34T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDl2hHqMyO6S6Ys0HeGh2I2-9H1tq6TZs',
    appId: '1:799466011826:android:e3b912d5c7d4eb84aaddab',
    messagingSenderId: '799466011826',
    projectId: 'smart-bus-26302',
    storageBucket: 'smart-bus-26302.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKR5wEC90gvhRgxuCHHtKENcWZd1EHXnw',
    appId: '1:799466011826:ios:41b8ea8640ce95caaaddab',
    messagingSenderId: '799466011826',
    projectId: 'smart-bus-26302',
    storageBucket: 'smart-bus-26302.appspot.com',
    iosClientId: '799466011826-2do93qrmrugi0b2pief88uiqk47km4pi.apps.googleusercontent.com',
    iosBundleId: 'com.bus.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKR5wEC90gvhRgxuCHHtKENcWZd1EHXnw',
    appId: '1:799466011826:ios:29b546f81bc365b6aaddab',
    messagingSenderId: '799466011826',
    projectId: 'smart-bus-26302',
    storageBucket: 'smart-bus-26302.appspot.com',
    iosClientId: '799466011826-s935jmihjvs5rd23fe3n1t3aph342bfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBus',
  );
}
